//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.28 at 10:27:21 AM CEST 
//


package fabermaster.utils.templater.model.restful;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for exposureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="exposureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bulk" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pathParams" type="{}paramType" maxOccurs="unbounded"/>
 *         &lt;element name="consumes" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="produces" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="headerParams" type="{}paramType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="queryParams" type="{}paramType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "exposureType", propOrder = {
    "method",
    "bulk",
    "name",
    "pathParams",
    "consumes",
    "produces",
    "headerParams",
    "queryParams"
})
public class ExposureType
    implements Serializable
{

    @XmlElement(required = true)
    protected String method;
    protected boolean bulk;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected List<ParamType> pathParams;
    protected List<String> consumes;
    protected List<String> produces;
    protected List<ParamType> headerParams;
    protected List<ParamType> queryParams;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMethod(String value) {
        this.method = value;
    }

    /**
     * Gets the value of the bulk property.
     * 
     */
    public boolean isBulk() {
        return bulk;
    }

    /**
     * Sets the value of the bulk property.
     * 
     */
    public void setBulk(boolean value) {
        this.bulk = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the pathParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getPathParams() {
        if (pathParams == null) {
            pathParams = new ArrayList<ParamType>();
        }
        return this.pathParams;
    }

    /**
     * Gets the value of the consumes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consumes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConsumes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConsumes() {
        if (consumes == null) {
            consumes = new ArrayList<String>();
        }
        return this.consumes;
    }

    /**
     * Gets the value of the produces property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the produces property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduces().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProduces() {
        if (produces == null) {
            produces = new ArrayList<String>();
        }
        return this.produces;
    }

    /**
     * Gets the value of the headerParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headerParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getHeaderParams() {
        if (headerParams == null) {
            headerParams = new ArrayList<ParamType>();
        }
        return this.headerParams;
    }

    /**
     * Gets the value of the queryParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamType }
     * 
     * 
     */
    public List<ParamType> getQueryParams() {
        if (queryParams == null) {
            queryParams = new ArrayList<ParamType>();
        }
        return this.queryParams;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
      StringBuilder builder = new StringBuilder();
      builder.append("ExposureType [method=");
      builder.append(method);
      builder.append(", bulk=");
      builder.append(bulk);
      builder.append(", name=");
      builder.append(name);
      builder.append(", pathParams=");
      builder.append(pathParams);
      builder.append(", consumes=");
      builder.append(consumes);
      builder.append(", produces=");
      builder.append(produces);
      builder.append(", headerParams=");
      builder.append(headerParams);
      builder.append(", queryParams=");
      builder.append(queryParams);
      builder.append("]");
      return builder.toString();
    }

    
}
