//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 12:51:52 PM CEST 
//


package fabermaster.utils.templater.model.restful;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fabermaster.utils.templater.model.restful package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fabermaster.utils.templater.model.restful
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntitySetting }
     * 
     */
    public EntitySetting createEntitySetting() {
        return new EntitySetting();
    }

    /**
     * Create an instance of {@link ExposureType }
     * 
     */
    public ExposureType createExposureType() {
        return new ExposureType();
    }

    /**
     * Create an instance of {@link ParamTypeSetting }
     * 
     */
    public ParamTypeSetting createParamTypeSetting() {
        return new ParamTypeSetting();
    }

    /**
     * Create an instance of {@link MethodSetting }
     * 
     */
    public MethodSetting createMethodSetting() {
        return new MethodSetting();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link Api }
     * 
     */
    public Api createApi() {
        return new Api();
    }

    /**
     * Create an instance of {@link SettingType }
     * 
     */
    public SettingType createSettingType() {
        return new SettingType();
    }

}
