//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 12:51:52 PM CEST 
//


package fabermaster.utils.templater.model.restful;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for settingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="pathParams" type="{}paramTypeSetting" maxOccurs="unbounded"/>
 *         &lt;element name="headerParams" type="{}paramTypeSetting" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="queryParams" type="{}entitySetting" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingType", propOrder = {
    "name",
    "pathParams",
    "headerParams",
    "queryParams"
})
public class SettingType
    implements Serializable
{

    @XmlElement(required = true)
    protected List<String> name;
    @XmlElement(required = true)
    protected List<ParamTypeSetting> pathParams;
    protected List<ParamTypeSetting> headerParams;
    protected List<EntitySetting> queryParams;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getName() {
        if (name == null) {
            name = new ArrayList<String>();
        }
        return this.name;
    }

    /**
     * Gets the value of the pathParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pathParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPathParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamTypeSetting }
     * 
     * 
     */
    public List<ParamTypeSetting> getPathParams() {
        if (pathParams == null) {
            pathParams = new ArrayList<ParamTypeSetting>();
        }
        return this.pathParams;
    }

    /**
     * Gets the value of the headerParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the headerParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeaderParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamTypeSetting }
     * 
     * 
     */
    public List<ParamTypeSetting> getHeaderParams() {
        if (headerParams == null) {
            headerParams = new ArrayList<ParamTypeSetting>();
        }
        return this.headerParams;
    }

    /**
     * Gets the value of the queryParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the queryParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQueryParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntitySetting }
     * 
     * 
     */
    public List<EntitySetting> getQueryParams() {
        if (queryParams == null) {
            queryParams = new ArrayList<EntitySetting>();
        }
        return this.queryParams;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {
      StringBuilder builder = new StringBuilder();
      builder.append("SettingType [name=");
      builder.append(name);
      builder.append(", pathParams=");
      builder.append(pathParams);
      builder.append(", headerParams=");
      builder.append(headerParams);
      builder.append(", queryParams=");
      builder.append(queryParams);
      builder.append("]");
      return builder.toString();
    }

   
}
